// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/go-eagle/eagle/pkg/app"
	"github.com/go-eagle/eagle/pkg/redis"
	"github.com/go-microservice/user-service/internal/cache"
	"github.com/go-microservice/user-service/internal/model"
	"github.com/go-microservice/user-service/internal/repository"
	"github.com/go-microservice/user-service/internal/server"
	"github.com/go-microservice/user-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func InitApp(cfg *app.Config, config *app.ServerConfig) (*app.App, error) {
	db := model.Init()
	client := redis.Init()
	userCache := cache.NewUserCache(client)
	userRepo := repository.NewUser(db, userCache)
	userServiceServer := service.NewUserServiceServer(userRepo)
	grpcServer := server.NewGRPCServer(config, userServiceServer)
	appApp := newApp(cfg, grpcServer)
	return appApp, nil
}
