// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/go-eagle/eagle/pkg/app"
	"github.com/go-microservice/user-service/internal/repository"
	"github.com/go-microservice/user-service/internal/server"
	"github.com/go-microservice/user-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func InitApp(cfg *app.Config, config *app.ServerConfig) (*app.App, error) {
	db := repository.NewGORMClient()
	userBaseRepo := repository.NewUserBase(db)
	userProfileRepo := repository.NewUserProfile(db)
	userServiceServer := service.NewUserServiceServer(userBaseRepo, userProfileRepo)
	grpcServer := server.NewGRPCServer(config, userServiceServer)
	appApp := newApp(cfg, grpcServer)
	return appApp, nil
}
