apiVersion: v1
kind: Service
metadata:
  name: user-svc
  labels:
    app: user-service
spec:
  ports:
    - name: user-svc-port
      port: 9001
      protocol: TCP
      #nodePort: 30002
      targetPort: 8080

  type: ClusterIP
  #type: NodePort
  selector:
    app: user-service